kind: pipeline
name: default

steps:
  - name: build
    image: node:10
    commands:
      - npm install
      - npm run build
    when:
      event:
        - push
      branch:
        - master
        - feat-*
