kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./node_modules
    volumes:
      - name: cache
        path: /cache
    when:
      event:
        - push

  - name: build
    image: node:10
    commands:
      - npm install
      - npm run build
    when:
      event:
        - push

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
    volumes:
      - name: cache
        path: /cache
    when:
      event:
        - push

  - name: docker build and push
    image: plugins/docker
    settings:
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      repo: keeet/web-app
      dockerfile: ./Dockerfile
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}

volumes:
  - name: cache
    host:
      path: /tmp
