apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-app-${DRONE_BRANCH}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web-app-${DRONE_BRANCH}
    spec:
      containers:
        - name: web-app-${DRONE_BRANCH}
          image: keeet/web-app:${DRONE_COMMIT_SHA}
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 10
      imagePullSecrets:
        - name: regcred
