export const PERSONA_ICONS = {
  CHANTAL: 'CHANTAL',
  JACQUELINE: 'JACQUELINE',
  MANDY: 'MANDY',
  KEVIN: 'KEVIN',
  MARVIN: 'MARVIN',
  JUSTIN: 'JUSTIN',
  DUSTIN: 'DUSTIN',
  JASON: 'JASON',
  MIKA: 'MIKA'
}

export const PERSONA_GENDERS = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  DIVERS: 'DIVERS'
}
export const PERSONA_GENDER_LABELS = {
  MALE: 'Male',
  FEMALE: 'Female',
  DIVERS: 'Divers'
}

export const PERSONA_OCCUPATIONS = {
  STUDENT: 'STUDENT',
  PART_TIME_EMPLOYEE: 'PART_TIME_EMPLOYEE',
  FULL_TIME_EMPLOYEE: 'FULL_TIME_EMPLOYEE',
  SELF_EMPLOYED: 'SELF_EMPLOYED',
  UNEMPLOYED: 'UNEMPLOYED',
  PENSIONER: 'PENSIONER',
  PUPIL: 'PUPIL',
  APPRENTICE: 'APPRENTICE'
}
export const PERSONA_OCCUPATION_LABELS = {
  STUDENT: 'Student',
  PART_TIME_EMPLOYEE: 'Part-time employee',
  FULL_TIME_EMPLOYEE: 'Full-time employee',
  SELF_EMPLOYED: 'Self employed',
  UNEMPLOYED: 'Unemployed',
  PENSIONER: 'Pensioner',
  PUPIL: 'Pupil',
  APPRENTICE: 'Apprentice'
}
