export const PERSONA_ICONS = {
  CHANTAL: 'CHANTAL',
  JACQUELINE: 'JACQUELINE',
  MANDY: 'MANDY',
  KEVIN: 'KEVIN',
  MARVIN: 'MARVIN',
  JUSTIN: 'JUSTIN',
  DUSTIN: 'DUSTIN',
  JASON: 'JASON',
  MIKA: 'MIKA'
}
